version: "3"
services:
  api:
    build:
      context: ai-api
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    links:
      - redis
    restart: unless-stopped

  redis:
    image: redis
    restart: unless-stopped

  worker:
    build:
      context: ai-api
      dockerfile: Dockerfile
    restart: unless-stopped
    links:
      - redis
    command: rq worker --url redis://redis:6379 --results-ttl 600

  client:
    depends_on:
      - api
      - worker
      - redis
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - 5000:5000
    environment:
      - WDS_SOCKET_PORT=0